<?php

namespace AppBundle\Repository;

/**
 * acces_supportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acces_supportRepository extends \Doctrine\ORM\EntityRepository
{
}
