<?php

namespace AppBundle\Repository;

/**
 * collaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class collaborateurRepository extends \Doctrine\ORM\EntityRepository
{
}
