<?php

namespace AppBundle\Repository;

/**
 * demande_sponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demande_sponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
