<?php

namespace AppBundle\Repository;

/**
 * jeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jeuRepository extends \Doctrine\ORM\EntityRepository
{
}
