<?php

namespace AppBundle\Repository;

/**
 * missionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class missionRepository extends \Doctrine\ORM\EntityRepository
{
}
