<?php

namespace AppBundle\Repository;

/**
 * postulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postulationRepository extends \Doctrine\ORM\EntityRepository
{
}
