<?php

namespace AppBundle\Repository;

/**
 * publicitéRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publicitéRepository extends \Doctrine\ORM\EntityRepository
{
}
