<?php

namespace AppBundle\Repository;

/**
 * sponsoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sponsoringRepository extends \Doctrine\ORM\EntityRepository
{
}
