<?php

namespace AppBundle\Repository;

/**
 * supportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class supportRepository extends \Doctrine\ORM\EntityRepository
{
}
