<?php

namespace AppBundle\Repository;

/**
 * type_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_evenementRepository extends \Doctrine\ORM\EntityRepository
{
}
