ahmed:
    resource: "@AhmedBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_homepage:
    path:     /admin
    defaults: { _controller: UserBundle:Default:AdminIndex }